chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('profile/<str:user>', views.profile, name='profile'),
    path('registrate/', views.registrate, name='registrate'),
    path('login/', views.lin, name='login'),
    path('logout/', views.lout, name='logout'),
    path('chat/', views.chat, name='chat'),
    path('chat/json/<int:number>', views.json_message, name='json_message'),
    path('chat/json/lm', views.lm_json, name='last_messages'),
    path('chat/send/', views.sendMessage, name='send'),
    path('changetheme/', views.change_theme, name='change_theme'),
    path('', views.otherwise, name='main'),
    path('<str:url>/', views.otherwise, name='otherwise')
]

lowchat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls')),
]

chat/models.py
from django.db import models

from django.contrib.auth.models import User

"""
class Chat(models.Model):
    name = models.CharField(max_length=128)
    users = models.ManyToManyField(User)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
"""


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # chat = models.ForeignKey(Chat, on_delete=models.CASCADE)
    text = models.CharField(max_length=1024)
    pub_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return (self.user.username + ' [' + str(self.pub_date.ctime()) + ']: ' + self.text[:32])

    class Meta:
        ordering = ('pub_date',)

    def gettime(self):
        time = self.pub_date.time()
        hour = time.hour
        minute = time.minute
        if hour < 10:
            hour = '0' + str(hour)
        else:
            hour = str(hour)
        if minute < 10:
            minute = '0' + str(minute)
        else:
            minute = str(minute)

        return hour + ':' + minute


class Features(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    image = models.ImageField(upload_to='staticfiles/chat/p_images/', max_length=100, default='static/chat/p_images/default.jpg')
    age = models.DateField()
    gender = models.CharField(max_length=1)
    information = models.CharField(max_length=1024)
    namecolor = models.CharField(max_length=32, default='black')
    last_enter = models.DateTimeField(auto_now=True)
    lr_message = models.IntegerField(default=0)
    theme = models.IntegerField(default=0)

    def __str__(self):
        return (self.user.username + ' features')

    def getimg(self):
        return '/static/' + '/'.join(self.image.url.split('/')[1:])

chat/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(max_length=64)
    password = forms.CharField(max_length=128)


class RegistrateForm(forms.Form):
    GENDERS = (
        ('N', 'None'),
        ('M', 'Male'),
        ('F', 'Female'),
    )
    COLORS = (
        ('black', 'black'),
    )
    username = forms.CharField(min_length=4, max_length=64)
    email = forms.EmailField()
    password = forms.CharField(min_length=8, max_length=128)
    image = forms.ImageField()
    age = forms.DateField(input_formats=['%Y-%m-%d'])
    gender = forms.ChoiceField(choices=GENDERS)
    namecolor = forms.CharField(max_length=7)
    information = forms.CharField(max_length=1024)


class MessageForm(forms.Form):
    text = forms.CharField(max_length=1024)

chat/views.py
from django.shortcuts import render, get_object_or_404

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from django.http import HttpResponseRedirect, JsonResponse

# from django.urls import reverse

from .models import Message, Features

from .forms import LoginForm, RegistrateForm, MessageForm

from django.utils import timezone


@login_required(login_url='/login')
def profile(request, user):
    html = 'profile.html'
    cur_username = request.user.username
    if (cur_username == user):
        html = 'current_profile.html'

    user = get_object_or_404(User, username=user)
    return render(request, 'chat/'+html, {'user': user})


def lin(request):
    error = False
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.data['username']
            password = form.data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect('/chat')
            else:
                error = True
    return render(request, 'chat/login.html', {'error': error})


def lout(request):
    logout(request)
    return HttpResponseRedirect('/login')


@login_required(login_url='/login')
def chat(request):
    user = request.user
    # Опасность при нуле сообщений!
    lm_id = Message.objects.last().id
    user.features.lr_message = lm_id
    lm = lm_id - 100
    if lm < 0:
        lm = 0
    messages = Message.objects.filter(id__gt=lm)
    request.user.features.last_enter = timezone.now()
    request.user.features.save()
    users_online = User.objects.filter(
        features__last_enter__gt=timezone.now()-timezone.timedelta(seconds=300)
    )
    return render(request, 'chat/chat.html',
                  {'user': user, 'users': users_online, 'messages': messages})


@login_required(login_url='/login')
def json_message(request, number):
    lm_id = Message.objects.last().id
    messages = Message.objects.filter(id__gt=lm_id-number)
    json = {}
    for message in messages:
        json[message.id] = {'username': message.user.username,
                            'time': message.gettime(), 'text': message.text}

    return JsonResponse(json, safe=False)


@login_required(login_url='/login')
def lm_json(request):
    user = request.user
    messages = Message.objects.filter(id__gt=user.features.lr_message)
    json = {}
    for message in messages:
        json[message.id] = {'username': message.user.username,
                            'time': message.gettime(),
                            'text': message.text
                            }

    return JsonResponse(json, safe=False)


@login_required(login_url='/login')
def sendMessage(request):
    form = MessageForm(request.POST)
    if form.is_valid():           # Здесь раньше была проверка на длинну текста
        Message(user=request.user, text=form.data['text']).save()
    return HttpResponseRedirect('/chat')


def change_theme(request):
    if request.user.is_authenticated:
        user = request.user
        if user.features.theme == 0:
            request.user.features.theme = 1
        else:
            request.user.features.theme = 0
        request.user.features.save()
        return JsonResponse({'status': 'ok'}, safe=False)
    else:
        return JsonResponse({'status': 'not authenticated'}, safe=False)


def registrate(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/chat')
    if request.method == 'POST':
        form = RegistrateForm(request.POST, request.FILES)
        data = form.data
        # for d in data:
        #    print(d + ':' + data[d])
        # print(form.is_valid())
        # print(form.errors)
        # print(form.files)
        user_exist = User.objects.filter(username=data['username']).count()
        if form.is_valid():
            if user_exist:
                return render(request, 'chat/registrate.html',
                              {'error': 'This user is exist'})
            user = User.objects.create_user(
                data['username'],
                data['email'],
                data['password']
            )
            Features(
                user=user,
                age=data['age'],
                gender=data['gender'],
                information=data['information'],
                namecolor=data['namecolor'],
                image=form.files['image']
            ).save()
            url = '/login'
        else:
            url = '/registrate'
        return HttpResponseRedirect(url)
    else:
        return render(request, 'chat/registrate.html')


@login_required(login_url='/login')
def otherwise(request, url='str'):
    return HttpResponseRedirect('/chat')

chat/templates/chat/chat.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport"
	content="width=device-width, user-scalable=yes, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Lowchat</title>
	<link rel="shortcut icon" href="{% static 'chat/img/leaf1.ico' %}">
    <link rel="stylesheet" href="{% static 'chat/css/chat.css' %}">
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
</head>
<body id="doc">
	<div class="container-wrapper">
		<div class="container">
			<span class="user-hi">Привет, <span class="user-hi__name" style="color:{{ user.features.namecolor }}">{{ user.username }}</span>!</span>
			<a href="/logout" class="user-goodbye">
				<button class="user-goodbye__button">Go out</button>
			</a>
			<div class="chat-frames-i">
				<div class="chat">
					<div id="frameScroll" class="chat__main-frame">
						{% for message in messages %}
	   						<div class="chat__user-text">
	   							<p class="chat__time">{{ message.gettime }}</p>
	   							<span class="chat__user-name" style="color:{{ message.user.features.namecolor }}">{{ message.user.username }}:<span class="chat__user-message">{{ message.text }}</span></span>
	   						</div>
						{% endfor %}
					</div>
               		<form class="chat__i" id="goMessage" action="{% url 'chat:send' %}" method="post">
						{% csrf_token %}
						<textarea type="text" name="text" class="chat__area" maxlength="1024" required id="id_text" autofocus rows="2"></textarea>
            <button id="buttonGo" class="chat__button" type="submit" value="send">go</button>
					</form>
				</div>
				<div class="users-list">
					{% for userr in users %}
					<div class="users-list__i">
						<img class="users-list__avatar" src="{{ userr.features.getimg }}" alt="img">
                        <span class="users-list__name chat__user-name" style="color:{{ userr.features.namecolor }}">{{ userr.username }}
                        </span>
					</div>
					{% endfor %}
				</div>
			</div>
		</div>
	</div>
	<script  type="text/javascript" src="{% static 'chat/js/scripts.js' %}"></script>
</body>
</html>

chat/templates/chat/login.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport"
	content="width=device-width, user-scalable=yes, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Lowchat</title>
	<link rel="shortcut icon" href="{% static 'chat/img/leaf1.ico' %}">
	<link rel="stylesheet" href="{% static 'chat/css/login.css' %}">
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
</head>
<body id="doc">
	<div class="container-wrapper">
		<div class="authorization-frame">
	        <form class="avtorization" action="{% url 'chat:login' %}" method="post">
				{% csrf_token %}
				<p class="login">Login: <br>
					<input autofocus class="login__input" maxlength="25" type="text" name="username">
				</p>
				<p class="password">Password: <br>
		    		<input class="password__input" type="password" maxlength="25" name="password">
		    	</p>
			<input type="submit" class="start-button" value="Start"> 
			</form>
			<p class="registration">Are you a stranger? <br>
				<a href="/registrate" class="registration__link">REGISTRATION</a>
			</p>
		</div>
	</div>
</body>
</html>

chat/templates/chat/registrate.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport"
	content="width=device-width, user-scalable=yes, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Lowchat</title>
	<link rel="shortcut icon" href="{% static 'chat/img/leaf1.ico' %}">
	<link rel="stylesheet" href="{% static 'chat/css/registrate.css' %}">
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
</head>
<body id="doc">
	<div class="container-wrapper">
		<div class="container">
			<div class="title-i">
			<h1 class="title">Registration form</h1>
			</div>
			<form enctype="multipart/form-data" class="container__i" action="/registrate/" method="post">
                {% csrf_token %}
				<div class="column1">
					<p for="id_username" class="username phrase">Username:</p>
					<input type="text" name="username" maxlength="64" minlength="4" required id="id_username" class="username__input indentation">
					<p for="id_password" class="password phrase">Password:</p>
					<input type="password" name="password" maxlength="128" minlength="8" required="" id="id_password" class="password__input indentation">
					<p for="id_email" class="email phrase">Email:</p>
					<input type="email" name="email" required id="id_email" class="email__input indentation">
					<p for="id_age" class="age phrase">Age:</p>
					<input type="date" name="age" id="id_age" class="age__input indentation" >
				</div>
				<div class="column2">
					<p for="id_image" class="image phrase">Image:</p>
					<img class="avatar" id="avatar" src="/static/chat/p_images/default.jpg" alt="img"><br>
					<input type="file" name="image" id="imgImp" class="image__input indentation"/>
					<p for="id_information" class="information phrase">About yourself:</p>
					<textarea type="text" name="information" maxlength="1024" id="id_information" class="information__input indentation"></textarea>
				</div>
				<div class="column3">
					<p for="id_gender" class="gender phrase">Gender:</p>
					<select name="gender" id="id_gender" class="gender__select indentation" >
						<option value="M" class="gender__option1">Male</option>
						<option value="F" class="gender__option2">Female</option>
					</select> 
					<p for="id_namecolor" class="namecolor phrase">Namecolor:</p>
					<input type="color" value="#375F1B" name="namecolor" id="id_color" class="namecolor__select indentation" >
					</input> <br>
					<button type="submit" value="registrate" class="sign-up">Sign up</button>
				</div>
			</form>
		</div>
	</div>
	<script src="{% static 'chat/js/registrate.js' %}"></script>
</body>
</html>
